<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class LigaDesaController extends Controller
{
    public function index()
    {
        // Data sementara (dummy) agar halaman web bisa dirender tanpa error
        $desas = [
            [
                'pos' => 1,
                'nama' => 'Desa Punten',
                'kecamatan' => 'Bumiaji',
                'skor' => 92.5,
                'tren' => '+2',
                'isUp' => true,
                'potensi' => 95,
                'digital' => 90,
                'ekonomi' => 92,
                'sosial' => 91,
                'sustainability' => 94,
                'img' => 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
                'program' => 'Agrohortikultura Cerdas & E-Commerce Desa',
                'desc' => 'Digitalisasi rantai pasok buah segar dan otomatisasi sistem irigasi.'
            ],
            [
                'pos' => 2,
                'nama' => 'Desa Sumbergondo',
                'kecamatan' => 'Bumiaji',
                'skor' => 89.7,
                'tren' => '+1',
                'isUp' => true,
                'potensi' => 92,
                'digital' => 88,
                'ekonomi' => 89,
                'sosial' => 90,
                'sustainability' => 89,
                'img' => 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=80',
                'program' => 'Bank Sampah Mandiri & Pengolahan Organik',
                'desc' => 'Pengelolaan limbah menjadi pupuk bernilai tinggi.'
            ],
            [
                'pos' => 3,
                'nama' => 'Desa Bulukerto',
                'kecamatan' => 'Bumiaji',
                'skor' => 87.3,
                'tren' => '+1',
                'isUp' => true,
                'potensi' => 88,
                'digital' => 86,
                'ekonomi' => 87,
                'sosial' => 88,
                'sustainability' => 87,
                'img' => 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80',
                'program' => 'Kampung Apel Wisata Edukasi Inovatif',
                'desc' => 'Integrasi turis lokal dengan pemetik buah mandiri dan transaksi QRIS.'
            ],
            [
                'pos' => 4,
                'nama' => 'Desa Oro-Oro Ombo',
                'kecamatan' => 'Batu',
                'skor' => 85.9,
                'tren' => '-1',
                'isUp' => false,
                'potensi' => 86,
                'digital' => 85,
                'ekonomi' => 88,
                'sosial' => 84,
                'sustainability' => 85,
                'img' => 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=800&q=80',
                'program' => 'Sentra Homestay Terpadu & Digital Ticketing',
                'desc' => 'Platform reservasi penginapan terpusat berbasis warga.'
            ],
            [
                'pos' => 5,
                'nama' => 'Desa Junrejo',
                'kecamatan' => 'Junrejo',
                'skor' => 84.2,
                'tren' => '-2',
                'isUp' => false,
                'potensi' => 85,
                'digital' => 83,
                'ekonomi' => 84,
                'sosial' => 82,
                'sustainability' => 86,
                'img' => 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
                'program' => 'Pasar Digital & UMKM Kreatif Lokal',
                'desc' => 'Platform e-commerce untuk produk lokal dan kerajinan tangan.'
            ],
            [
                'pos' => 6,
                'nama' => 'Desa Tlekung',
                'kecamatan' => 'Bumiaji',
                'skor' => 82.8,
                'tren' => '+1',
                'isUp' => true,
                'potensi' => 83,
                'digital' => 81,
                'ekonomi' => 82,
                'sosial' => 80,
                'sustainability' => 84,
                'img' => 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=80',
                'program' => 'Wisata Edukasi Pertanian & Agroforestry',
                'desc' => 'Program edukasi pertanian berkelanjutan untuk wisatawan dan pelajar.'
            ],
            [
                'pos' => 7,
                'nama' => 'Desa Pandanrejo',
                'kecamatan' => 'Bumiaji',
                'skor' => 81.5,
                'tren' => '-1',
                'isUp' => false,
                'potensi' => 82,
                'digital' => 80,
                'ekonomi' => 81,
                'sosial' => 79,
                'sustainability' => 83,
                'img' => 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80',
                'program' => 'Kampung Wisata Kreatif & Digital Marketing',
                'desc' => 'Pelatihan pemasaran digital untuk UMKM lokal dan kerajinan tangan.'
            ],
            [
                'pos' => 8,
                'nama' => 'Desa Giripurno',
                'kecamatan' => 'Bumiaji',
                'skor' => 80.3,
                'tren' => '+2',
                'isUp' => true,
                'potensi' => 81,
                'digital' => 79,
                'ekonomi' => 80,
                'sosial' => 78,
                'sustainability' => 82,
                'img' => 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=800&q=80',
                'program' => 'Agrowisata Edukatif & Pemberdayaan Komunitas',
                'desc' => 'Program pemberdayaan masyarakat melalui agrowisata dan edukasi pertanian.'
            ],
            [
                'pos' => 9,
                'nama' => 'Desa Sumberbrantas',
                'kecamatan' => 'Bumiaji',
                'skor' => 79.1,
                'tren' => '-1',
                'isUp' => false,
                'potensi' => 80,
                'digital' => 78,
                'ekonomi' => 79,
                'sosial' => 77,
                'sustainability' => 81,
                'img' => 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
                'program' => 'Sentra Kerajinan Tangan & E-Commerce Lokal',
                'desc' => 'Pengembangan kerajinan tangan lokal dan pemasaran melalui platform digital.'
            ],
            [
                'pos' => 10,
                'nama' => 'Desa Mojorejo',
                'kecamatan' => 'Bumiaji',
                'skor' => 77.8,
                'tren' => '+1',
                'isUp' => true,
                'potensi' => 78,
                'digital' => 76,
                'ekonomi' => 77,
                'sosial' => 75,
                'sustainability' => 80,
                'img' => 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80',
                'program' => 'Wisata Alam & Edukasi Lingkungan Berkelanjutan',
                'desc' => 'Program edukasi lingkungan dan wisata alam yang berkelanjutan.'
            ],
            [
                'pos' => 11,
                'nama' => 'Desa Tlekung',
                'kecamatan' => 'Bumiaji',
                'skor' => 76.5,
                'tren' => '-2',
                'isUp' => false,
                'potensi' => 77,
                'digital' => 75,
                'ekonomi' => 76,
                'sosial' => 74,
                'sustainability' => 79,
                'img' => 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=800&q=80',
                'program' => 'Agrowisata Edukatif & Pemberdayaan Komunitas',
                'desc' => 'Program pemberdayaan masyarakat melalui agrowisata dan edukasi pertanian.'
            ],
            [
                'pos' => 12,
                'nama' => 'Desa Pandanrejo',
                'kecamatan' => 'Bumiaji',
                'skor' => 75.2,
                'tren' => '+1',
                'isUp' => true,
                'potensi' => 76,
                'digital' => 74,
                'ekonomi' => 75,
                'sosial' => 73,
                'sustainability' => 78,
                'img' => 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
                'program' => 'Sentra Kerajinan Tangan & E-Commerce Lokal',
                'desc' => 'Pengembangan kerajinan tangan lokal dan pemasaran melalui platform digital.'
            ],
            [
                'pos' => 13,
                'nama' => 'Desa Giripurno',
                'kecamatan' => 'Bumiaji',
                'skor' => 74.0,
                'tren' => '-1',
                'isUp' => false,
                'potensi' => 75,
                'digital' => 73,
                'ekonomi' => 74,
                'sosial' => 72,
                'sustainability' => 77,
                'img' => 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80',
                'program' => 'Wisata Alam & Edukasi Lingkungan Berkelanjutan',
                'desc' => 'Program edukasi lingkungan dan wisata alam yang berkelanjutan.'
            ],
            [
                'pos' => 14,
                'nama' => 'Desa Sumberbrantas',
                'kecamatan' => 'Bumiaji',
                'skor' => 72.8,
                'tren' => '+2',
                'isUp' => true,
                'potensi' => 73,
                'digital' => 71,
                'ekonomi' => 72,
                'sosial' => 70,
                'sustainability' => 75,
                'img' => 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
                'program' => 'Agrowisata Edukatif & Pemberdayaan Komunitas',
                'desc' => 'Program pemberdayaan masyarakat melalui agrowisata dan edukasi pertanian.'
            ],
            [
                'pos' => 15,
                'nama' => 'Desa Mojorejo',
                'kecamatan' => 'Bumiaji',
                'skor' => 71.5,
                'tren' => '-1',
                'isUp' => false,
                'potensi' => 72,
                'digital' => 70,
                'ekonomi' => 71,
                'sosial' => 69,
                'sustainability' => 74,
                'img' => 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=800&q=80',
                'program' => 'Sentra Kerajinan Tangan & E-Commerce Lokal',
                'desc' => 'Pengembangan kerajinan tangan lokal dan pemasaran melalui platform digital.'
            ],
            [
                'pos' => 16,
                'nama' => 'Desa Tlekung',
                'kecamatan' => 'Bumiaji',
                'skor' => 70.2,
                'tren' => '+1',
                'isUp' => true,
                'potensi' => 71,
                'digital' => 69,
                'ekonomi' => 70,
                'sosial' => 68,
                'sustainability' => 73,
                'img' => 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
                'program' => 'Wisata Alam & Edukasi Lingkungan Berkelanjutan',
                'desc' => 'Program edukasi lingkungan dan wisata alam yang berkelanjutan.'
            ],
            [
                'pos' => 17,
                'nama' => 'Desa Pandanrejo',
                'kecamatan' => 'Bumiaji',
                'skor' => 69.0,
                'tren' => '-2',
                'isUp' => false,
                'potensi' => 70,
                'digital' => 68,
                'ekonomi' => 69,
                'sosial' => 67,
                'sustainability' => 72,
                'img' => 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80',
                'program' => 'Agrowisata Edukatif & Pemberdayaan Komunitas',
                'desc' => 'Program pemberdayaan masyarakat melalui agrowisata dan edukasi pertanian.'
            ],
            [
                'pos' => 18,
                'nama' => 'Desa Giripurno',
                'kecamatan' => 'Bumiaji',
                'skor' => 67.8,
                'tren' => '+1',
                'isUp' => true,
                'potensi' => 68,
                'digital' => 66,
                'ekonomi' => 67,
                'sosial' => 65,
                'sustainability' => 70,
                'img' => 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
                'program' => 'Sentra Kerajinan Tangan & E-Commerce Lokal',
                'desc' => 'Pengembangan kerajinan tangan lokal dan pemasaran melalui platform digital.'
            ],
            [
                'pos' => 19,
                'nama' => 'Desa Sumberbrantas',
                'kecamatan' => 'Bumiaji',
                'skor' => 66.5,
                'tren' => '-1',
                'isUp' => false,
                'potensi' => 67,
                'digital' => 65,
                'ekonomi' => 66,
                'sosial' => 64,
                'sustainability' => 69,
                'img' => 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=800&q=80',
                'program' => 'Wisata Alam & Edukasi Lingkungan Berkelanjutan',
                'desc' => 'Program edukasi lingkungan dan wisata alam yang berkelanjutan.'
            ],
            [
                'pos' => 20,
                'nama' => 'Desa Mojorejo',
                'kecamatan' => 'Bumiaji',
                'skor' => 65.2,
                'tren' => '+2',
                'isUp' => true,
                'potensi' => 66,
                'digital' => 64,
                'ekonomi' => 65,
                'sosial' => 63,
                'sustainability' => 68,
                'img' => 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
                'program' => 'Agrowisata Edukatif & Pemberdayaan Komunitas',
                'desc' => 'Program pemberdayaan masyarakat melalui agrowisata dan edukasi pertanian.'
            ],
            [
                'pos' => 21,
                'nama' => 'Desa Tlekung',
                'kecamatan' => 'Bumiaji',
                'skor' => 64.0,
                'tren' => '-1',
                'isUp' => false,
                'potensi' => 65,
                'digital' => 63,
                'ekonomi' => 64,
                'sosial' => 62,
                'sustainability' => 67,
                'img' => 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80',
                'program' => 'Sentra Kerajinan Tangan & E-Commerce Lokal',
                'desc' => 'Pengembangan kerajinan tangan lokal dan pemasaran melalui platform digital.'
            ],
            [
                'pos' => 22,
                'nama' => 'Desa Pandanrejo',
                'kecamatan' => 'Bumiaji',
                'skor' => 62.8,
                'tren' => '+1',
                'isUp' => true,
                'potensi' => 63,
                'digital' => 61,
                'ekonomi' => 62,
                'sosial' => 60,
                'sustainability' => 65,
                'img' => 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
                'program' => 'Wisata Alam & Edukasi Lingkungan Berkelanjutan',
                'desc' => 'Program edukasi lingkungan dan wisata alam yang berkelanjutan.'
            ],
            [
                'pos' => 23,
                'nama' => 'Desa Giripurno',
                'kecamatan' => 'Bumiaji',
                'skor' => 61.5,
                'tren' => '-2',
                'isUp' => false,
                'potensi' => 62,
                'digital' => 60,
                'ekonomi' => 61,
                'sosial' => 59,
                'sustainability' => 64,
                'img' => 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=800&q=80',
                'program' => 'Agrowisata Edukatif & Pemberdayaan Komunitas',
                'desc' => 'Program pemberdayaan masyarakat melalui agrowisata dan edukasi pertanian.'
            ],
            [
                'pos' => 24,
                'nama' => 'Desa Sumberbrantas',
                'kecamatan' => 'Bumiaji',
                'skor' => 60.3,
                'tren' => '+1',
                'isUp' => true,
                'potensi' => 61,
                'digital' => 59,
                'ekonomi' => 60,
                'sosial' => 58,
                'sustainability' => 63,
                'img' => 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
                'program' => 'Sentra Kerajinan Tangan & E-Commerce Lokal',
                'desc' => 'Pengembangan kerajinan tangan lokal dan pemasaran melalui platform digital.'
            ],
            [
                'pos' => 25,
                'nama' => 'Desa Mojorejo',
                'kecamatan' => 'Bumiaji',
                'skor' => 59.0,
                'tren' => '-1',
                'isUp' => false,
                'potensi' => 60,
                'digital' => 58,
                'ekonomi' => 59,
                'sosial' => 57,
                'sustainability' => 62,
                'img' => 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80',
                'program' => 'Wisata Alam & Edukasi Lingkungan Berkelanjutan',
                'desc' => 'Program edukasi lingkungan dan wisata alam yang berkelanjutan.'
            ],
            
        ];

        return view('liga-desa', compact('desas'));
    }
}